assert_consistent – Inference-Engine
assert_consistent Subroutine
14 statements
Source File
pure subroutine assert_consistent(self)
Arguments
Type Intent Optional Attributes Name
type(inference_engine_t), intent(in) :: self
Calls
Called by
Contents
None
Call graph
assert_consistent calls assert, num_neurons, output_count, intrinsic_array_t
conformable_with calls assert_consistent, conformable_with
write_network calls assert_consistent, write_network
to_json calls assert_consistent, to_json
construct_from_json calls assert_consistent
infer_from_inputs_object calls assert_consistent, infer_from_inputs_object
construct_from_components calls assert_consistent
neurons_per_layer calls assert_consistent, neurons_per_layer
infer_from_array_of_inputs calls assert_consistent, infer_from_array_of_inputs
norm calls assert_consistent, norm
num_hidden_layers calls assert_consistent, num_hidden_layers
num_inputs calls assert_consistent, num_inputs
num_outputs calls assert_consistent, num_outputs
read_network calls assert_consistent, read_network
subtract calls assert_consistent, subtract