assert_conformable_with – Inference-Engine
assert_conformable_with Module Procedure
8 statements
Source File
module procedure assert_conformable_with elemental module module subroutine assert_conformable_with(self, inference_engine) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
type(inference_engine_t), intent(in) :: inference_engine
Calls
Called by
Contents
None
Call graph
assert_conformable_with calls assert_consistency, assert, intrinsic_array_t, assert_conformable_with
assert_consistency calls inference_engine_consistency, difference_consistency
inference_engine_consistency calls assert, intrinsic_array_t
difference_consistency calls assert, intrinsic_array_t