construct_from_json – Inference-Engine
construct_from_json Module Procedure
74 statements
Source File
module procedure construct_from_json impure elemental module function construct_from_json(file_) result(inference_engine)
Arguments
Type Intent Optional Attributes Name
type(file_t), intent(in) :: file_
Return Value type(inference_engine_t)
Calls
Call graph
construct_from_json calls assert, assert_consistency, count_layers, count_neurons, inference_engine, to_json, lines, set_activation_strategy, string, string_t
assert_consistency calls difference_consistency, inference_engine_consistency
set_activation_strategy calls string
difference_consistency calls assert, intrinsic_array_t
inference_engine_consistency calls assert, intrinsic_array_t