construct_from_legacy_arrays – Inference-Engine
construct_from_legacy_arrays Procedure
46 statements
Source File
module procedure construct_from_legacy_arrays module procedure construct_from_legacy_arrays()
Arguments
None
Calls
Contents
None
Call graph
construct_from_legacy_arrays calls hidden_weights, assert_consistent, set_activation_strategy, n, assert_consistency
assert_consistent calls assert, num_neurons, output_count, intrinsic_array_t
assert_consistency calls assert, intrinsic_array_t