construct_from_padded_arrays – Inference-Engine
construct_from_padded_arrays Module Procedure
30 statements
Source File
module procedure construct_from_padded_arrays impure module function construct_from_padded_arrays(metadata, weights, biases, nodes, input_range, output_range) result(inference_engine)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(in) :: metadata(:)
real(kind=rkind), intent(in) :: weights(:,:,:)
real(kind=rkind), intent(in) :: biases(:,:)
integer, intent(in) :: nodes(0:)
type(tensor_range_t), intent(in), optional :: input_range
type(tensor_range_t), intent(in), optional :: output_range
Return Value type(inference_engine_t)
Calls
Call graph
construct_from_padded_arrays calls assert_consistency, activation_factory_method, string
assert_consistency calls difference_consistency, inference_engine_consistency
difference_consistency calls assert, intrinsic_array_t
inference_engine_consistency calls assert, intrinsic_array_t