construct_layer – Inference-Engine
construct_layer Module Procedure
23 statements
Source File
module procedure construct_layer recursive module function construct_layer(layer_lines, start) result(layer)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(in) :: layer_lines(:)
integer, intent(in) :: start
Return Value type(layer_t), target
Calls
Call graph
construct_layer calls assert, next_allocated, next_pointer, weights, string