default_real_construct_layer – Fiats
default_real_construct_layer Module Procedure
23 statements
Source File
module procedure default_real_construct_layer recursive module function default_real_construct_layer(layer_lines, start) result(layer)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(in) :: layer_lines(:)
integer, intent(in) :: start
Return Value type(layer_t), target
Calls
Call graph
default_real_construct_layer calls assert, next_allocated, next_pointer, weights, string