default_real_infer – Fiats
default_real_infer Module Procedure
19 statements
Source File
module procedure default_real_infer elemental module function default_real_infer(self, inputs) result(outputs) Interface →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t), intent(in) :: self
type(tensor_t), intent(in) :: inputs
Return Value type(tensor_t)
Calls
Call graph
default_real_infer calls assert_consistency, evaluate, map_from_training_range, map_to_training_range, values