default_real_neural_network – Fiats
default_real_neural_network Module Procedure
49 statements
Source File
module procedure default_real_neural_network module function default_real_neural_network(hidden_layers, metadata, output_layer, input_map, output_map) result(neural_network_) Interface →
Arguments
Type Intent Optional Attributes Name
class(layer_t), intent(in), target :: hidden_layers
type(string_t), intent(in) :: metadata(:)
type(layer_t), intent(in), target :: output_layer
type(tensor_map_t), intent(in) :: input_map
type(tensor_map_t), intent(in) :: output_map
Return Value type(neural_network_t)
Calls
Call graph
default_real_neural_network calls assert, bias, biases, next_allocated, next_pointer, count_inputs, count_layers, count_neurons, weights