difference_consistency – Inference-Engine
difference_consistency Subroutine
8 statements
Source File
pure subroutine difference_consistency(self)
Arguments
Type Intent Optional Attributes Name
type(difference_t), intent(in) :: self
Calls
Called by
Call graph
difference_consistency calls assert, intrinsic_array_t
assert_consistency calls difference_consistency
assert_conformable_with calls assert_consistency
construct_from_padded_arrays calls assert_consistency
from_json calls assert_consistency
infer calls assert_consistency
nodes_per_layer calls assert_consistency
num_hidden_layers calls assert_consistency
num_inputs calls assert_consistency
num_outputs calls assert_consistency
subtract calls assert_consistency
to_json calls assert_consistency