double_precision_construct_from_components – Fiats
double_precision_construct_from_components Module Procedure
31 statements
Source File
module procedure double_precision_construct_from_components module function double_precision_construct_from_components(metadata, weights, biases, nodes, input_map, output_map) result(neural_network)
Arguments
Type Intent Optional Attributes Name
type(metadata_t), intent(in) :: metadata
double precision, intent(in) :: weights(:,:,:)
double precision, intent(in) :: biases(:,:)
integer, intent(in) :: nodes(0:)
type(tensor_map_t(double_precision)), intent(in), optional :: input_map
type(tensor_map_t(double_precision)), intent(in), optional :: output_map
Return Value type(neural_network_t(double_precision))
Calls
Call graph
double_precision_construct_from_components calls activation_name, assert_consistency, string