double_precision_from_json – Fiats
double_precision_from_json Module Procedure
15 statements
Source File
module procedure double_precision_from_json pure module function double_precision_from_json(lines) result(hyperparameters)
Arguments
Type Intent Optional Attributes Name
type(double_precision_string_t), intent(in) :: lines(:)
Return Value type(hyperparameters_t(double_precision))
Calls
Call graph
double_precision_from_json calls assert, get_json_key, get_json_value, string_t