double_precision_approximately_equal – Fiats
double_precision_approximately_equal Module Procedure
18 statements
Source File
module procedure double_precision_approximately_equal elemental module function double_precision_approximately_equal(lhs, rhs) result(lhs_eq_rhs) Interface →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t(double_precision)), intent(in) :: lhs
class(neural_network_t(double_precision)), intent(in) :: rhs
Return Value logical
Calls
Call graph
double_precision_approximately_equal calls layer_eq, assert_conformable_with, assert_consistency