from_json – Inference-Engine
from_json Module Procedure
87 statements
Source File
module procedure from_json impure elemental module function from_json(file_) result(inference_engine)
Arguments
Type Intent Optional Attributes Name
type(file_t), intent(in) :: file_
Return Value type(inference_engine_t)
Calls
Call graph
from_json calls assert, assert_consistency, count_layers, count_neurons, inference_engine, strings, to_json, lines, activation_factory_method, string, string_t
assert_consistency calls difference_consistency, inference_engine_consistency
difference_consistency calls assert, intrinsic_array_t
inference_engine_consistency calls assert, intrinsic_array_t