from_json – Inference-Engine
from_json Module Procedure
15 statements
Source File
module procedure from_json pure module function from_json(lines) result(hyperparameters)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(in) :: lines(:)
Return Value type(hyperparameters_t)
Calls
Call graph
from_json calls assert, get_json_key, get_json_value, string_t