GAMMP – Inference-Engine
GAMMP Function
16 statements
Source File
public function GAMMP(A, X)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: A
real, intent(in) :: X
Return Value real
Calls
Called by
Contents
Source Code
GAMMP
Source Code
      REAL FUNCTION GAMMP(A,X)
!     --- COMPUTES THE INCOMPLETE GAMMA FUNCTION P(A,X)
!     --- SEE ABRAMOWITZ AND STEGUN 6.5.1
!     --- USES GCF,GSER
      IMPLICIT NONE
      REAL, INTENT(IN):: A,X
      REAL:: GAMMCF,GAMSER,GLN
      GAMMP = 0.
      IF((X.LT.0.) .OR. (A.LE.0.)) THEN
        PRINT *, 'BAD ARGUMENTS IN GAMMP'
        RETURN
      ELSEIF(X.LT.A+1.)THEN
        CALL GSER(GAMSER,A,X,GLN)
        GAMMP=GAMSER
      ELSE
        CALL GCF(GAMMCF,A,X,GLN)
        GAMMP=1.-GAMMCF
      ENDIF
      END FUNCTION GAMMP
Call graph
gammp calls gser, gcf
gser calls gammln
gcf calls gammln
qi_aut_qs calls gammp
table_dropevap calls gammp