get_shape – Inference-Engine
get_shape Function
27 statements
Source File
function get_shape(ncid, varname) result(array_shape)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ncid
character(len=*), intent(in) :: varname
Return Value integer, allocatable, (:)
Calls
Called by
Call graph
get_shape calls assert, nf90_inq_varid, nf90_inquire_dimension, nf90_inquire_variable, nf90_strerror
input_1d_double calls get_shape
input_2d_integer calls get_shape
input_3d_real calls get_shape
input_4d_real calls get_shape