inference_engine_consistency – Inference-Engine
inference_engine_consistency Module Subroutine
13 statements
Source File
pure module subroutine inference_engine_consistency(self)
Arguments
Type Intent Optional Attributes Name
type(inference_engine_t), intent(in) :: self
Calls
Called by
Contents
None
Call graph
inference_engine_consistency calls intrinsic_array_t, assert
assert_consistency calls inference_engine_consistency
assert_conformable_with calls assert_consistency, assert_conformable_with
construct_from_padded_arrays calls assert_consistency
num_inputs calls assert_consistency, num_inputs
infer calls assert_consistency, infer
nodes_per_layer calls assert_consistency, nodes_per_layer
num_outputs calls assert_consistency, num_outputs
subtract calls assert_consistency, subtract
to_json calls assert_consistency, to_json
construct_from_json calls assert_consistency