inference_engine – Inference-Engine
inference_engine Module Procedure
49 statements
Source File
module procedure inference_engine module module function inference_engine(hidden_layers, metadata, output_layer) result(inference_engine_) Interface →
Arguments
Type Intent Optional Attributes Name
class(layer_t), intent(in), target :: hidden_layers
type(string_t), intent(in) :: metadata(:)
type(layer_t), intent(in), target :: output_layer
Return Value type(inference_engine_t)
Calls
Called by
Contents
None
Call graph
inference_engine calls assert, weights, biases, inference_engine