infer_from_inputs_object – Inference-Engine
infer_from_inputs_object Module Procedure
5 statements
Source File
module procedure infer_from_inputs_object elemental module module function infer_from_inputs_object(self, inputs, inference_strategy) result(outputs) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
type(inputs_t), intent(in) :: inputs
class(inference_strategy_t), intent(in) :: inference_strategy
Return Value type(outputs_t)
Calls
Called by
Contents
None
Call graph
infer_from_inputs_object calls assert_consistent, infer_from_inputs_object
assert_consistent calls assert_consistent, assert, num_neurons, output_count, intrinsic_array_t