infer – Inference-Engine
infer Module Procedure
20 statements
Source File
module procedure infer elemental module function infer(self, inputs) result(outputs) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
type(tensor_t), intent(in) :: inputs
Return Value type(tensor_t)
Calls
Call graph
infer calls activation, assert_consistency, map_from_training_range, map_to_training_range, values
assert_consistency calls difference_consistency, inference_engine_consistency
difference_consistency calls assert, intrinsic_array_t
inference_engine_consistency calls assert, intrinsic_array_t