input_2D_integer – Inference-Engine
input_2D_integer Module Procedure
18 statements
Source File
module procedure input_2D_integer module subroutine input_2D_integer(self, varname, values) Interface →
Arguments
Type Intent Optional Attributes Name
class(NetCDF_file_t), intent(in) :: self
character(len=*), intent(in) :: varname
integer, intent(out), allocatable :: values(:,:)
Calls
Call graph
input_2d_integer calls assert, nf90_get_var, nf90_inq_varid, nf90_open, nf90_strerror, get_shape
get_shape calls assert, nf90_inq_varid, nf90_strerror, nf90_inquire_dimension, nf90_inquire_variable