input_1D_double – Inference-Engine
input_1D_double Module Procedure
18 statements
Source File
module procedure input_1D_double module subroutine input_1D_double(self, varname, values) Interface →
Arguments
Type Intent Optional Attributes Name
class(NetCDF_file_t), intent(in) :: self
character(len=*), intent(in) :: varname
double precision, intent(out), allocatable :: values(:)
Calls
Call graph
input_1d_double calls assert, intrinsic_array_t, nf90_get_var, nf90_inq_varid, nf90_open, nf90_strerror, get_shape
get_shape calls assert, nf90_inq_varid, nf90_strerror, nf90_inquire_dimension, nf90_inquire_variable