input_4D_real – Inference-Engine
input_4D_real Module Procedure
18 statements
Source File
module procedure input_4D_real module subroutine input_4D_real(self, varname, values) Interface →
Arguments
Type Intent Optional Attributes Name
class(NetCDF_file_t), intent(in) :: self
character(len=*), intent(in) :: varname
real, intent(out), allocatable :: values(:,:,:,:)
Calls
Call graph
input_4d_real calls assert, intrinsic_array_t, nf90_get_var, nf90_inq_varid, nf90_open, nf90_strerror, get_shape
get_shape calls assert, nf90_inq_varid, nf90_strerror, nf90_inquire_dimension, nf90_inquire_variable