map_to_training_ranges – Inference-Engine
map_to_training_ranges Module Procedure
7 statements
Source File
module procedure map_to_training_ranges elemental module function map_to_training_ranges(self, input_output_pair) result(normalized_input_output_pair) Interface →
Arguments
Type Intent Optional Attributes Name
class(trainable_engine_t), intent(in) :: self
type(input_output_pair_t), intent(in) :: input_output_pair
Return Value type(input_output_pair_t)
Calls
Call graph
map_to_training_ranges calls expected_outputs, inputs, map_to_training_range