mp_gt_driver – Inference-Engine
mp_gt_driver Subroutine
100 statements
Source File
public subroutine mp_gt_driver(qv, qc, qr, qi, qs, qg, ni, nr, th, pii, p, dz, dt_in, itimestep, RAINNC, RAINNCV, SNOWNC, SNOWNCV, GRAUPELNC, GRAUPELNCV, SR, ids, ide, jds, jde, kds, kde, ims, ime, jms, jme, kms, kme, its, ite, jts, jte, kts, kte)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: qv
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: qc
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: qr
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: qi
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: qs
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: qg
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: ni
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: nr
real, intent(inout), DIMENSION(ims:ime, kms:kme, jms:jme) :: th
real, intent(in), DIMENSION(ims:ime, kms:kme, jms:jme) :: pii
real, intent(in), DIMENSION(ims:ime, kms:kme, jms:jme) :: p
real, intent(in), DIMENSION(ims:ime, kms:kme, jms:jme) :: dz
real, intent(in) :: dt_in
integer, intent(in) :: itimestep
real, intent(inout), DIMENSION(ims:ime, jms:jme) :: RAINNC
real, intent(inout), DIMENSION(ims:ime, jms:jme) :: RAINNCV
real, intent(inout), optional DIMENSION(ims:ime, jms:jme) :: SNOWNC
real, intent(inout), optional DIMENSION(ims:ime, jms:jme) :: SNOWNCV
real, intent(inout), optional DIMENSION(ims:ime, jms:jme) :: GRAUPELNC
real, intent(inout), optional DIMENSION(ims:ime, jms:jme) :: GRAUPELNCV
real, intent(inout), DIMENSION(ims:ime, jms:jme) :: SR
integer, intent(in) :: ids
integer, intent(in) :: ide
integer, intent(in) :: jds
integer, intent(in) :: jde
integer, intent(in) :: kds
integer, intent(in) :: kde
integer, intent(in) :: ims
integer, intent(in) :: ime
integer, intent(in) :: jms
integer, intent(in) :: jme
integer, intent(in) :: kms
integer, intent(in) :: kme
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: jts
integer, intent(in) :: jte
integer, intent(in) :: kts
integer, intent(in) :: kte
Calls
Contents
Source Code
mp_gt_driver
Source Code
      SUBROUTINE mp_gt_driver(qv, qc, qr, qi, qs, qg, ni, nr, &
                              th, pii, p, dz, dt_in, itimestep, &
                              RAINNC, RAINNCV, &
                              SNOWNC, SNOWNCV, &
                              GRAUPELNC, GRAUPELNCV, SR, &
                              ids,ide, jds,jde, kds,kde, &             ! domain dims
                              ims,ime, jms,jme, kms,kme, &             ! memory dims
                              its,ite, jts,jte, kts,kte)               ! tile dims
      implicit none
!..Subroutine arguments
      INTEGER, INTENT(IN):: ids,ide, jds,jde, kds,kde, &
                            ims,ime, jms,jme, kms,kme, &
                            its,ite, jts,jte, kts,kte
      REAL, DIMENSION(ims:ime, kms:kme, jms:jme), INTENT(INOUT):: &
                          qv, qc, qr, qi, qs, qg, ni, nr, th
      REAL, DIMENSION(ims:ime, kms:kme, jms:jme), INTENT(IN):: &
                          pii, p, dz
      REAL, DIMENSION(ims:ime, jms:jme), INTENT(INOUT):: &
                          RAINNC, RAINNCV, SR
      REAL, DIMENSION(ims:ime, jms:jme), OPTIONAL, INTENT(INOUT)::      &
                          SNOWNC, SNOWNCV, GRAUPELNC, GRAUPELNCV
!     REAL, DIMENSION(ims:ime, kms:kme, jms:jme), INTENT(INOUT)::       &
!                         refl_10cm
      REAL, INTENT(IN):: dt_in
!..Local variables
      INTEGER, INTENT(IN):: itimestep
      REAL, DIMENSION(kts:kte):: &
                          qv1d, qc1d, qi1d, qr1d, qs1d, qg1d, ni1d, &
                          nr1d, t1d, p1d, dz1d, dBZ
!       REAL, DIMENSION(its:ite, jts:jte):: pcp_ra, pcp_sn, pcp_gr, pcp_ic
      REAL:: dt, pptrain, pptsnow, pptgraul, pptice
      REAL:: qc_max, qr_max, qs_max, qi_max, qg_max, ni_max, nr_max
      INTEGER:: i, j, k
      INTEGER:: imax_qc,imax_qr,imax_qi,imax_qs,imax_qg,imax_ni,imax_nr
      INTEGER:: jmax_qc,jmax_qr,jmax_qi,jmax_qs,jmax_qg,jmax_ni,jmax_nr
      INTEGER:: kmax_qc,kmax_qr,kmax_qi,kmax_qs,kmax_qg,kmax_ni,kmax_nr
      INTEGER:: i_start, j_start, i_end, j_end
!$OMP PARALLEL DEFAULT(PRIVATE) FIRSTPRIVATE(ids,ide,jds,jde,kds,kde,ims,ime,jms,jme,&
!$OMP kms,kme,its,ite,jts,jte,kts,kte,itimestep) &
!$OMP SHARED(RAINNCV,RAINNC,SNOWNCV,SNOWNC,GRAUPELNCV,GRAUPELNC,SR,th,pii,p,dz,qv,qc,&
!$OMP qi,qr,qs,qg,ni,nr,dt_in,Nt_c,TNO,rho_g,av_s,bv_s,fv_s,av_g,bv_g,EF_si,Ef_ri)
! old w/pcp_xx vars !!$OMP qi,qr,qs,qg,ni,nr,pcp_ra,pcp_sn,pcp_gr,pcp_ic,dt_in)
      i_start = its
      j_start = jts
      i_end   = MIN(ite, ide-1)
      j_end   = MIN(jte, jde-1)
!..For idealized testing by developer.
!     if ((ide-ids+1).gt.4 .and. (jde-jds+1).lt.4 .and.                &
!          ids.eq.its.and.ide.eq.ite.and.jds.eq.jts.and.jde.eq.jte) then
!        i_start = its + 2
!        i_end   = ite
!        j_start = jts
!        j_end   = jte
!     endif
      dt = dt_in
      qc_max = 0.
      qr_max = 0.
      qs_max = 0.
      qi_max = 0.
      qg_max = 0
      ni_max = 0.
      nr_max = 0.
      imax_qc = 0
      imax_qr = 0
      imax_qi = 0
      imax_qs = 0
      imax_qg = 0
      imax_ni = 0
      imax_nr = 0
      jmax_qc = 0
      jmax_qr = 0
      jmax_qi = 0
      jmax_qs = 0
      jmax_qg = 0
      jmax_ni = 0
      jmax_nr = 0
      kmax_qc = 0
      kmax_qr = 0
      kmax_qi = 0
      kmax_qs = 0
      kmax_qg = 0
      kmax_ni = 0
      kmax_nr = 0
!       do i = 1, 256
!          mp_debug(i:i) = char(0)
!       enddo
!$omp do schedule(guided)
      j_loop:  do j = j_start, j_end
      i_loop:  do i = i_start, i_end
         pptrain = 0.
         pptsnow = 0.
         pptgraul = 0.
         pptice = 0.
!          RAINNCV(i,j) = 0.
!          IF (PRESENT (snowncv)) THEN
!             SNOWNCV(i,j) = 0.
!          ENDIF
!          IF (PRESENT (graupelncv)) THEN
!             GRAUPELNCV(i,j) = 0.
!          ENDIF
!          SR(i,j) = 0.
         do k = kts, kte
            t1d(k) = th(i,k,j)*pii(i,k,j)
            p1d(k) = p(i,k,j)
            dz1d(k) = dz(i,k,j)
            qv1d(k) = qv(i,k,j)
            qc1d(k) = qc(i,k,j)
            qi1d(k) = qi(i,k,j)
            qr1d(k) = qr(i,k,j)
            qs1d(k) = qs(i,k,j)
            qg1d(k) = qg(i,k,j)
            ni1d(k) = ni(i,k,j)
            nr1d(k) = nr(i,k,j)
         enddo
         call mp_thompson(qv1d, qc1d, qi1d, qr1d, qs1d, qg1d, ni1d, &
                      nr1d, t1d, p1d, dz1d, &
                      pptrain, pptsnow, pptgraul, pptice, &
                      kts, kte, dt, i, j)
!          pcp_ra(i,j) = pptrain
!          pcp_sn(i,j) = pptsnow
!          pcp_gr(i,j) = pptgraul
!          pcp_ic(i,j) = pptice
!          RAINNCV(i,j) = pptrain + pptsnow + pptgraul + pptice
         RAINNC(i,j) = RAINNC(i,j) + pptrain + pptsnow + pptgraul + pptice
         IF ( PRESENT(SNOWNC) ) SNOWNC(i,j) = SNOWNC(i,j) + pptsnow + pptice
         IF ( PRESENT(SNOWNCV) )     SNOWNCV(i,j) = pptsnow + pptice
         IF ( PRESENT(GRAUPELNC) ) GRAUPELNC(i,j) = GRAUPELNC(i,j) + pptgraul
         IF ( PRESENT(GRAUPELNCV) )    GRAUPELNCV(i,j) = pptgraul
         SR(i,j) = (pptsnow + pptgraul + pptice)/(RAINNCV(i,j)+1.e-12)
         do k = kts, kte
            qv(i,k,j) = qv1d(k)
            qc(i,k,j) = qc1d(k)
            qi(i,k,j) = qi1d(k)
            qr(i,k,j) = qr1d(k)
            qs(i,k,j) = qs1d(k)
            qg(i,k,j) = qg1d(k)
            ni(i,k,j) = ni1d(k)
            nr(i,k,j) = nr1d(k)
            th(i,k,j) = t1d(k)/pii(i,k,j)
!             if (qc1d(k) .gt. qc_max) then
!              imax_qc = i
!              jmax_qc = j
!              kmax_qc = k
!              qc_max = qc1d(k)
!             elseif (qc1d(k) .lt. 0.0) then
!              write(mp_debug,*) 'WARNING, negative qc ', qc1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
!             endif
!             if (qr1d(k) .gt. qr_max) then
!              imax_qr = i
!              jmax_qr = j
!              kmax_qr = k
!              qr_max = qr1d(k)
!             elseif (qr1d(k) .lt. 0.0) then
!              write(mp_debug,*) 'WARNING, negative qr ', qr1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
!             endif
!             if (nr1d(k) .gt. nr_max) then
!              imax_nr = i
!              jmax_nr = j
!              kmax_nr = k
!              nr_max = nr1d(k)
!             elseif (nr1d(k) .lt. 0.0) then
!              write(mp_debug,*) 'WARNING, negative nr ', nr1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
!             endif
!             if (qs1d(k) .gt. qs_max) then
!              imax_qs = i
!              jmax_qs = j
!              kmax_qs = k
!              qs_max = qs1d(k)
!             elseif (qs1d(k) .lt. 0.0) then
!              write(mp_debug,*) 'WARNING, negative qs ', qs1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
!             endif
!             if (qi1d(k) .gt. qi_max) then
!              imax_qi = i
!              jmax_qi = j
!              kmax_qi = k
!              qi_max = qi1d(k)
!             elseif (qi1d(k) .lt. 0.0) then
!              write(mp_debug,*) 'WARNING, negative qi ', qi1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
!             endif
!             if (qg1d(k) .gt. qg_max) then
!              imax_qg = i
!              jmax_qg = j
!              kmax_qg = k
!              qg_max = qg1d(k)
!             elseif (qg1d(k) .lt. 0.0) then
!              write(mp_debug,*) 'WARNING, negative qg ', qg1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
!             endif
!             if (ni1d(k) .gt. ni_max) then
!              imax_ni = i
!              jmax_ni = j
!              kmax_ni = k
!              ni_max = ni1d(k)
!             elseif (ni1d(k) .lt. 0.0) then
!              write(mp_debug,*) 'WARNING, negative ni ', ni1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
!             endif
            if (qv1d(k) .lt. 1.E-7) then
             if (k.lt.kte-2 .and. k.gt.kts+1) then
                qv(i,k,j) = 0.5*(qv(i,k-1,j) + qv(i,k+1,j))
                ! note, if qv(i,k+1,j) < 0 then qv(i,k,j) could still be < 0
                if (qv1d(k) .lt. 1.E-7) then
                    qv(i,k,j) = 1.E-7
                endif
             else
                qv(i,k,j) = 1.E-7
             endif
!              write(mp_debug,*) 'WARNING, negative qv ', qv1d(k),        &
!                         ' at i,j,k=', i,j,k
             ! CALL wrf_debug(150, mp_debug)
            endif
         enddo
!          IF (PRESENT (diagflag)) THEN
!          if (diagflag .and. do_radar_ref == 1) then
!           call calc_refl10cm (qv1d, qc1d, qr1d, nr1d, qs1d, qg1d,       &
!                       t1d, p1d, dBZ, kts, kte, i, j)
!           do k = kts, kte
!              refl_10cm(i,k,j) = MAX(-35., dBZ(k))
!           enddo
!          endif
!          ENDIF
      enddo i_loop
      enddo j_loop
      !$omp end do
      !$omp end parallel
! DEBUG - GT
!       write(mp_debug,'(a,7(a,e13.6,1x,a,i3,a,i3,a,i3,a,1x))') 'MP-GT:', &
!          'qc: ', qc_max, '(', imax_qc, ',', jmax_qc, ',', kmax_qc, ')', &
!          'qr: ', qr_max, '(', imax_qr, ',', jmax_qr, ',', kmax_qr, ')', &
!          'qi: ', qi_max, '(', imax_qi, ',', jmax_qi, ',', kmax_qi, ')', &
!          'qs: ', qs_max, '(', imax_qs, ',', jmax_qs, ',', kmax_qs, ')', &
!          'qg: ', qg_max, '(', imax_qg, ',', jmax_qg, ',', kmax_qg, ')', &
!          'ni: ', ni_max, '(', imax_ni, ',', jmax_ni, ',', kmax_ni, ')', &
!          'nr: ', nr_max, '(', imax_nr, ',', jmax_nr, ',', kmax_nr, ')'
      ! CALL wrf_debug(150, mp_debug)
! END DEBUG - GT
!       do i = 1, 256
!          mp_debug(i:i) = char(0)
!       enddo
      END SUBROUTINE mp_gt_driver
Call graph
mp_gt_driver calls mp_thompson
mp_thompson calls rslf, sngl, alog10, rsif