netCDF_read – Inference-Engine
netCDF_read Subroutine
17 statements
Source File
subroutine netCDF_read(file_name_, data_in)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: file_name_
integer, intent(inout), allocatable :: data_in(:,:)
Calls
Called by
Contents
None
Call graph
netcdf_read calls nf90_strerror, assert, data_in_shape
netcdf_io calls netcdf_read