neurons_per_layer – Inference-Engine
neurons_per_layer Module Procedure
4 statements
Source File
module procedure neurons_per_layer elemental module module function neurons_per_layer(self) result(neuron_count) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value integer
Calls
Called by
Contents
None
Call graph
neurons_per_layer calls assert_consistent, neurons_per_layer
assert_consistent calls assert_consistent, assert, output_count, intrinsic_array_t, num_neurons