nodes_per_layer – Inference-Engine
nodes_per_layer Module Procedure
4 statements
Source File
module procedure nodes_per_layer pure module module function nodes_per_layer(self) result(node_count) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value integer,allocatable,(:)
Calls
Called by
Contents
None
Call graph
nodes_per_layer calls assert_consistency, nodes_per_layer
assert_consistency calls inference_engine_consistency, difference_consistency
inference_engine_consistency calls intrinsic_array_t, assert
difference_consistency calls intrinsic_array_t, assert