nodes_per_layer – Inference-Engine
nodes_per_layer Module Procedure
4 statements
Source File
module procedure nodes_per_layer pure module function nodes_per_layer(self) result(node_count) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value integer, allocatable, (:)
Calls
Call graph
nodes_per_layer calls assert_consistency
assert_consistency calls difference_consistency, inference_engine_consistency
difference_consistency calls assert, intrinsic_array_t
inference_engine_consistency calls assert, intrinsic_array_t