num_inputs – Inference-Engine
num_inputs Module Procedure
4 statements
Source File
module procedure num_inputs elemental module module function num_inputs(self) result(input_count) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value integer
Calls
Called by
Contents
None
Call graph
num_inputs calls assert_consistency, num_inputs
assert_consistency calls inference_engine_consistency, difference_consistency
inference_engine_consistency calls intrinsic_array_t, assert
difference_consistency calls intrinsic_array_t, assert