num_hidden_layers – Inference-Engine
num_hidden_layers Module Procedure
4 statements
Source File
module procedure num_hidden_layers elemental module module function num_hidden_layers(self) result(hidden_layer_count) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value integer
Calls
Called by
Contents
None
Call graph
num_hidden_layers calls assert_consistent, num_hidden_layers
assert_consistent calls assert_consistent, assert, intrinsic_array_t, num_neurons, output_count