perturbed_identity_network – Inference-Engine
perturbed_identity_network Function
16 statements
Source File
function perturbed_identity_network(perturbation_magnitude) result(trainable_engine)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: perturbation_magnitude
Return Value type(trainable_engine_t)
Calls
Called by
Call graph
perturbed_identity_network calls e, string_t
learn_addition calls perturbed_identity_network