set_activation_strategy – Inference-Engine
set_activation_strategy Subroutine
17 statements
Source File
pure subroutine set_activation_strategy(inference_engine)
Arguments
Type Intent Optional Attributes Name
type(inference_engine_t), intent(inout) :: inference_engine
Calls
Called by
Call graph
set_activation_strategy calls string
construct_from_json calls set_activation_strategy
construct_from_padded_arrays calls set_activation_strategy