single_hidden_layer_xor_network – Inference-Engine
single_hidden_layer_xor_network Function
6 statements
Source File
function single_hidden_layer_xor_network() result(inference_engine)
Arguments
None
Return Value type(inference_engine_t)
Calls
Called by
Contents
None
Call graph
single_hidden_layer_xor_network calls string_t
write_read_query_infer calls single_hidden_layer_xor_network
write_read_infer calls write_read_query_infer