subtract – Inference-Engine
subtract Module Procedure
24 statements
Source File
module procedure subtract elemental module function subtract(self, rhs) result(difference) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
type(inference_engine_t), intent(in) :: rhs
Return Value type(difference_t)
Calls
Call graph
subtract calls assert_conformable_with, assert_consistency
assert_consistency calls difference_consistency, inference_engine_consistency
difference_consistency calls assert, intrinsic_array_t
inference_engine_consistency calls assert, intrinsic_array_t