to_json – Inference-Engine
to_json Module Procedure
116 statements
Source File
module procedure to_json impure elemental module module function to_json(self) result(json_file) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value type(file_t)
Calls
Called by
Contents
None
Call graph
to_json calls string_t, file_t, separated_values, n, assert_consistency, assert, hidden_layer_weights, intrinsic_array_t, to_json
assert_consistency calls inference_engine_consistency, difference_consistency
inference_engine_consistency calls assert, intrinsic_array_t
difference_consistency calls assert, intrinsic_array_t