to_json – Inference-Engine
to_json Module Procedure
135 statements
Source File
module procedure to_json impure elemental module function to_json(self) result(json_file) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value type(file_t)
Calls
Call graph
to_json calls assert, file_t, hidden_layer_weights, input_range_json, assert_consistency, num_inputs, num_outputs, to_json, intrinsic_array_t, output_range_json, separated_values, string, string_t
assert_consistency calls difference_consistency, inference_engine_consistency
difference_consistency calls assert, intrinsic_array_t
inference_engine_consistency calls assert, intrinsic_array_t