train – Inference-Engine
train Module Procedure
132 statements
Source File
module procedure train pure module subroutine train(self, mini_batches_arr, cost, adam, learning_rate) Interface →
Arguments
Type Intent Optional Attributes Name
class(trainable_engine_t), intent(inout) :: self
type(mini_batch_t), intent(in) :: mini_batches_arr(:)
real(kind=rkind), intent(out), optional, allocatable :: cost(:)
logical, intent(in) :: adam
real(kind=rkind), intent(in) :: learning_rate
Calls
Call graph
train calls activation, activation_derivative, beta, expected_outputs, inputs, assert_consistent, input_output_pairs, num_inputs, num_layers, values, local, obeta, pair_cost, reduce, reduce_dcdb, reduce_dcdw