write_network – Inference-Engine
write_network Module Procedure
42 statements
Source File
module procedure write_network impure elemental module module subroutine write_network(self, file_name) Interface →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
type(string_t), intent(in) :: file_name
Calls
Called by
Contents
None
Call graph
write_network calls assert, assert_consistent, write_network
assert_consistent calls assert, num_neurons, intrinsic_array_t, output_count