write_read_query_infer – Inference-Engine
write_read_query_infer Subroutine
31 statements
Source File
subroutine write_read_query_infer(output_file_name)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(in) :: output_file_name
Calls
Called by
Contents
Source Code
write_read_query_infer
Source Code
  subroutine write_read_query_infer(output_file_name)
    type(string_t), intent(in) :: output_file_name
    type(string_t) activation_name
    integer i, j
    integer, parameter :: num_inputs = 2, num_outputs = 1, num_neurons = 3, num_hidden_layers = 2
    integer, parameter :: identity(*,*,*) = &
      reshape([((merge(1,0,i==j), i=1,num_neurons), j=1,num_neurons)], shape=[num_neurons,num_neurons,num_hidden_layers-1])
    type(inference_engine_t) xor_network, inference_engine
    type(file_t) json_output_file, json_input_file
    type(outputs_t) network_outputs
    print *, "Constructing an inference_engine_t neural-network object from scratch."
    xor_network = inference_engine_t( &
      metadata = [string_t("XOR"), string_t("Damian Rouson"), string_t("2023-02-18"), string_t("step"), string_t("false")], &
      input_weights = real(reshape([1,0,1,1,0,1], [num_inputs, num_neurons]), rkind), &
      hidden_weights = real(identity, rkind), &
      output_weights = real(reshape([1,-2,1], [num_outputs, num_neurons]), rkind), &
      biases = reshape([real(rkind):: 0.,-1.99,0., 0.,0.,0.], [num_neurons, num_hidden_layers]), &
      output_biases = [real(rkind):: 0.] &
    )
    print *, "Converting an inference_engine_t object to a file_t object."
    json_output_file = xor_network%to_json()
    print *, "Writing an inference_engine_t object to the file '"//output_file_name%string()//"' in JSON format."
    call json_output_file%write_lines(output_file_name)
    print *, "Reading an inference_engine_t object from the same JSON file '"//output_file_name%string()//"'."
    json_input_file = file_t(output_file_name)
    print *, "Constructing a new inference_engine_t object from the parameters read."
    inference_engine = inference_engine_t(json_input_file)
    print *, "Querying the new inference_engine_t object for several properties:"
    print *, "number of outputs:", inference_engine%num_outputs()
    print *, "number of hidden layers:", inference_engine%num_hidden_layers()
    print *, "number of neurons per layer:", inference_engine%neurons_per_layer()
    activation_name = inference_engine%activation_function_name()
    print *, "activation function: ", activation_name%string()
    print *, "using skip connections: ", merge("true ", "false", inference_engine%skip())
    print *, "Performing inference:"
    network_outputs = inference_engine%infer([real(rkind):: 0.,1.], matmul_t())
    print *, "inference_engine%infer([0.,1.]) =", network_outputs%outputs()
    print *, "Correct answer for the XOR neural network: ", 1.
  end subroutine write_read_query_infer
Call graph
write_read_query_infer calls string_t, file_t
write_read_infer calls write_read_query_infer