assert_consistency – Inference-Engine
assert_consistency Interface
4 statements
Source File
private interface assert_consistency
Calls
Called by
Contents
Module Procedures
inference_engine_consistency difference_consistency
Module Procedures
pure module subroutine inference_engine_consistency(self)
Arguments
Type Intent Optional Attributes Name
type(inference_engine_t), intent(in) :: self
pure module subroutine difference_consistency(self)
Arguments
Type Intent Optional Attributes Name
type(difference_t), intent(in) :: self
Call graph
assert_consistency calls inference_engine_consistency, difference_consistency
inference_engine_consistency calls intrinsic_array_t, assert
difference_consistency calls intrinsic_array_t, assert
assert_conformable_with calls assert_consistency, assert_conformable_with
num_inputs calls assert_consistency, num_inputs
infer calls assert_consistency, infer
nodes_per_layer calls assert_consistency, nodes_per_layer
num_outputs calls assert_consistency, num_outputs
subtract calls assert_consistency, subtract
to_json calls assert_consistency, to_json
construct_from_json calls assert_consistency
construct_from_padded_arrays calls assert_consistency