default_real_next_pointer – Fiats
default_real_next_pointer Interface
62 statements
Source File
interface
Called by
private module function default_real_next_pointer(self) result(next_ptr) Implementation →
Arguments
Type Intent Optional Attributes Name
class(neuron_t), intent(in), target :: self
Return Value type(neuron_t),pointer
Call graph
default_real_construct_layer calls next_pointer
default_real_count_neurons calls next_pointer
default_real_neurons_per_layer calls next_pointer
double_precision_construct_layer calls next_pointer
double_precision_count_neurons calls next_pointer
double_precision_neurons_per_layer calls next_pointer