default_real_count_neurons – Fiats
default_real_count_neurons Interface
78 statements
Source File
interface
Called by
private module function default_real_count_neurons(layer) result(neurons_per_layer_result) Implementation →
Arguments
Type Intent Optional Attributes Name
class(layer_t), intent(in), target :: layer
Return Value integer,allocatable,(:)
Call graph
default_real_from_json calls count_neurons
default_real_neural_network calls count_neurons
double_precision_from_json calls count_neurons
double_precision_neural_network calls count_neurons