default_real_num_hidden_layers – Fiats
default_real_num_hidden_layers Interface
145 statements
Source File
interface
Called by
private elemental module function default_real_num_hidden_layers(self) result(hidden_layer_count) Implementation →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t), intent(in) :: self
Return Value integer
Call graph
default_real_learn calls num_hidden_layers
default_real_to_json calls num_hidden_layers
double_precision_to_json calls num_hidden_layers