default_real_next_allocated – Fiats
default_real_next_allocated Interface
62 statements
Source File
interface
Called by
private module function default_real_next_allocated(self) result(next_is_allocated) Implementation →
Arguments
Type Intent Optional Attributes Name
class(neuron_t), intent(in) :: self
Return Value logical
Call graph
default_real_construct_layer calls next_allocated
default_real_count_neurons calls next_allocated
default_real_neurons_per_layer calls next_allocated
double_precision_construct_layer calls next_allocated
double_precision_count_neurons calls next_allocated
double_precision_neurons_per_layer calls next_allocated