default_real_map_to_training_range – Fiats
default_real_map_to_training_range Interface
46 statements
Source File
interface
Called by
private elemental module function default_real_map_to_training_range(self, tensor) result(normalized_tensor) Implementation →
Arguments
Type Intent Optional Attributes Name
class(tensor_map_t), intent(in) :: self
type(tensor_t), intent(in) :: tensor
Return Value type(tensor_t)
Call graph
default_real_infer calls map_to_training_range
default_real_map_to_input_range calls map_to_training_range
double_precision_infer calls map_to_training_range
double_precision_map_to_input_range calls map_to_training_range