default_real_num_outputs – Fiats
default_real_num_outputs Interface
145 statements
Source File
interface
Called by
private elemental module function default_real_num_outputs(self) result(output_count) Implementation →
Arguments
Type Intent Optional Attributes Name
class(neural_network_t), intent(in) :: self
Return Value integer
Call graph
default_real_to_json calls num_outputs
double_precision_to_json calls num_outputs
write_read_query_infer calls num_outputs
read_query_infer calls num_outputs
write_read_infer calls write_read_query_infer