double_precision_values – Fiats
double_precision_values Interface
22 statements
Source File
interface
Called by
private pure module function double_precision_values(self) result(tensor_values) Implementation →
Arguments
Type Intent Optional Attributes Name
class(tensor_t(double_precision)), intent(in) :: self
Return Value double precision,allocatable,(:)
Call graph
default_real_infer_unmapped calls values
default_real_learn calls values
default_real_map_from_training_range calls values
default_real_map_to_training_range calls values
default_real_write_to_stdout calls values
double_precision_infer_unmapped calls values
double_precision_map_from_training_range calls values
double_precision_map_to_training_range calls values
double_precision_write_to_stdout calls values
write_read_query_infer calls values
y calls values
read_query_infer calls values
learn_addition calls y
learn_exponentiation calls y
learn_multiplication calls y
learn_power_series calls y
train_saturated_mixture_ratio calls y
write_read_infer calls write_read_query_infer