num_outputs – Inference-Engine
num_outputs Interface
54 statements
Source File
interface
Calls
private elemental module module function num_outputs(self) result(output_count) Implementation →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(in) :: self
Return Value integer
Call graph
num_outputs calls num_outputs, assert_consistency
assert_consistency calls inference_engine_consistency, difference_consistency
inference_engine_consistency calls intrinsic_array_t, assert
difference_consistency calls intrinsic_array_t, assert