read_network – Inference-Engine
read_network Interface
56 statements
Source File
interface
Calls
private impure elemental module module subroutine read_network(self, file_name, activation_strategy) Implementation →
Arguments
Type Intent Optional Attributes Name
class(inference_engine_t), intent(out) :: self
type(string_t), intent(in) :: file_name
class(activation_strategy_t), intent(in), optional :: activation_strategy
Call graph
read_network calls read_network, assert, assert_consistent
assert_consistent calls assert, intrinsic_array_t