values – Inference-Engine
values Interface
12 statements
Source File
interface
Called by
private pure module function values(self) result(tensor_values) Implementation →
Arguments
Type Intent Optional Attributes Name
class(tensor_t), intent(in) :: self
Return Value real(kind=rkind),allocatable,(:)
Call graph
bin calls values
in_range calls values
map_from_training_range calls values
map_to_training_range calls values
train calls values
write_read_query_infer calls values
write_to_stdout calls values
y calls values
read_query_infer calls values
learn_addition calls y
learn_exponentiation calls y
learn_microphysics_procedures calls y
learn_multiplication calls y
learn_power_series calls y
train_saturated_mixture_ratio calls y
write_read_infer calls write_read_query_infer