concurrent_inferences – Inference-Engine
concurrent_inferences Program
63 statements
Source File
Uses
iso_fortran_env
julienne_m
inference_engine_m
assert_m
This program demonstrates how to read a neural network from a JSON file and use the network to perform concurrent inferences.
Calls
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(string_t) :: network_file_name
Call graph
concurrent_inferences calls assert, file_t, flag_value, infer, input_components, inputs, num_inputs, outputs, string, string_t