convert_to_json – Inference-Engine
convert_to_json Program
38 statements
Source File
Uses
sigmoid_m
command_line_m
inference_engine_m
file_m
kind_parameters_m
string_m
matmul_m
assert_m
This program demonstrates how to read a neural network in a custom file format into an inference_engine_t object, convert it to a JSON format, and write the resulting JSON objects to a file.
Calls
Contents
Variables
command_line inference_engine input_file_name json_output_file
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(inference_engine_t) :: inference_engine
character(len=:), allocatable :: input_file_name
type(file_t) :: json_output_file
Call graph
convert_to_json calls string_t, inputs, assert