icar_qr_network – Inference-Engine
icar_qr_network Program
33 statements
Source File
Uses
outputs_m
inference_engine_m
matmul_m
command_line_m
file_m
string_m
kind_parameters_m
This program demonstrates how to read a neural network from a JSON file. query the network for a some of its properties.
Calls
Contents
Variables
activation_name command_line inference_engine input_file_name
Variables
Type Attributes Name Initial
type(string_t) :: activation_name
type(command_line_t) :: command_line
type(inference_engine_t) :: inference_engine
type(string_t) :: input_file_name
Call graph
icar_qr_network calls string_t, inputs, file_t