learn_microphysics_procedures – Inference-Engine
learn_microphysics_procedures Program
168 statements
Source File
Uses
sourcery_m
iso_fortran_env
assert_m
inference_engine_m
thompson_tensors_m
Train a neural network proxies for procedures in the Thompson microphysics model in of ICAR (https://github.com/BerkeleyLab/icar).
Calls
Contents
Variables
clock_rate command_line counter_end counter_start network_file
Functions
e perturbed_identity_network
Subroutines
open_plot_file_for_appending output print_diagnostics
Variables
Type Attributes Name Initial
integer(kind=int64) :: clock_rate
type(command_line_t) :: command_line
integer(kind=int64) :: counter_end
integer(kind=int64) :: counter_start
type(string_t) :: network_file
Functions
pure function e(j, n) result(unit_vector)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
integer, intent(in) :: n
Return Value real,allocatable, (:)
function perturbed_identity_network(perturbation_magnitude, n) result(trainable_engine)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: perturbation_magnitude
integer, intent(in) :: n(:)
Return Value type(trainable_engine_t)
Subroutines
subroutine open_plot_file_for_appending(plot_file_name, plot_unit, previous_epoch, previous_clock)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: plot_file_name
integer, intent(out) :: plot_unit
integer, intent(out) :: previous_epoch
real, intent(out) :: previous_clock
subroutine output(inference_engine, file_name)
Arguments
Type Intent Optional Attributes Name
type(inference_engine_t), intent(in) :: inference_engine
type(string_t), intent(in) :: file_name
subroutine print_diagnostics(plot_file_unit, epoch, cost, clock, nodes)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: plot_file_unit
integer, intent(in) :: epoch
real, intent(in) :: cost
real, intent(in) :: clock
integer, intent(in) :: nodes(:)
Call graph
learn_microphysics_procedures calls inputs, network_outputs, file_t, cost, nodes_per_layer, intrinsic_array_t, mini_batches, output, output_sizes, desired_outputs, random_numbers, perturbed_identity_network, string_t, input_output_pairs, assert, bin_t, shuffle, print_diagnostics, bins, y, random_init, open_plot_file_for_appending
perturbed_identity_network calls string_t, e
shuffle calls shuffle, assert
y calls assert, rsif, rslf
open_plot_file_for_appending calls file_t, string_t