learn_power_series – Inference-Engine
learn_power_series Program
95 statements
Source File
Uses
power_series
inference_engine_m
sourcery_m
assert_m
This trains a neural network to learn the following six polynomial functions of its eight inputs.
Calls
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(string_t) :: final_network_file
type(string_t) :: intial_network_file
Functions
pure function e(j, n) result(unit_vector)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
integer, intent(in) :: n
Return Value real, allocatable, (:)
function perturbed_identity_network(perturbation_magnitude) result(trainable_engine)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: perturbation_magnitude
Return Value type(trainable_engine_t)
Subroutines
subroutine output(inference_engine, file_name)
Arguments
Type Intent Optional Attributes Name
type(inference_engine_t), intent(in) :: inference_engine
type(string_t), intent(in) :: file_name
Call graph
learn_power_series calls assert, bin_t, bins, cost, desired_outputs, first, flag_value, infer, input_output_pairs, inputs, shuffle, intrinsic_array_t, last, mini_batches, num_inputs, num_outputs, output_sizes, output, perturbed_identity_network, y, random_init, random_numbers, string, string_t, to_inference_engine, train, values, white_noise
output calls to_json, write_lines
perturbed_identity_network calls string_t, e
y calls assert, values