read_query_infer – Inference-Engine
read_query_infer Program
38 statements
Source File
Uses
inference_engine_m
kind_parameters_m
julienne_m
This program demonstrates how to read a neural network from a JSON file, query the network object for some of its properties, print those properties, and use the network to perform inference.
Calls
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
Call graph
read_query_infer calls file_t, flag_value, harvest, activation_function_name, infer, nodes_per_layer, num_inputs, num_outputs, values, random_init, string, string_t