read_and_infer – Inference-Engine
read_and_infer Program
30 statements
Source File
Uses
inference_engine_m
kind_parameters_m
command_line_m
assert_m
string_m
matmul_m
sigmoid_m
This program demonstrates how to 1. Read a neural network from a file into an inference_engine_t object, 2. Query the object for some of its properties (number of inputs, etc.), and 3. User the object to perform inference This example expects 10 inputs and applies a sigmoid activation function.
Calls
Contents
Variables
command_line inference_engine input_file_name
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(inference_engine_t) :: inference_engine
character(len=:), allocatable :: input_file_name
Call graph
read_and_infer calls string_t, inputs, assert