train_polynomials – Inference-Engine
train_polynomials Program
98 statements
Source File
Uses
assert_m
inference_engine_m
sourcery_m
This trains a neural network to learn the following six polynomial functions of its eight inputs.
Calls
Contents
Variables
command_line final_network_file intial_network_file
Functions
e perturbed_identity_network y
Subroutines
output
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(string_t) :: final_network_file
type(string_t) :: intial_network_file
Functions
pure function e(j, n) result(unit_vector)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: j
integer, intent(in) :: n
Return Value real,allocatable, (:)
function perturbed_identity_network(perturbation_magnitude) result(trainable_engine)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: perturbation_magnitude
Return Value type(trainable_engine_t)
elemental function y(x_tensor) result(a_tensor)
Arguments
Type Intent Optional Attributes Name
type(tensor_t), intent(in) :: x_tensor
Return Value type(tensor_t)
Subroutines
subroutine output(inference_engine, file_name)
Arguments
Type Intent Optional Attributes Name
type(inference_engine_t), intent(in) :: inference_engine
type(string_t), intent(in) :: file_name
Call graph
train_polynomials calls desired_outputs, random_init, input_output_pairs, cost, y, intrinsic_array_t, assert, bin_t, string_t, inputs, mini_batches, bins, random_numbers, perturbed_identity_network, output, shuffle, network_outputs
y calls assert, x
perturbed_identity_network calls string_t, e
shuffle calls shuffle, assert