train_xor_gate – Inference-Engine
train_xor_gate Program
74 statements
Source File
Uses
sigmoid_m
trainable_engine_m
file_m
command_line_m
string_m
matmul_m
input_output_pair_m
mini_batch_m
outputs_m
inputs_m
expected_outputs_m
kind_parameters_m
Define inference tests and procedures required for reporting results
Calls
Contents
Variables
actual_output base_name command_line expected_outputs false i inputs m mini_batches table_entry tolerance trainable_engine true
Functions
wide_perceptron wide_single_layer_perceptron
Subroutines
output
Source Code
train_xor_gate
Variables
Type Attributes Name Initial
type(outputs_t), dimension(4) :: actual_output
type(string_t) :: base_name
type(command_line_t) :: command_line
type(expected_outputs_t), dimension(4) :: expected_outputs
real(kind=rkind), parameter :: false = 0._rkind
integer :: i
type(inputs_t), allocatable :: inputs(:)
integer :: m
type(mini_batch_t), allocatable :: mini_batches(:)
character(len=5), parameter :: table_entry(*) = ["TT->F", "FT->T", "TF->T", "FF->F", "xor "]
real(kind=rkind), parameter :: tolerance = 1.E-02_rkind
type(trainable_engine_t) :: trainable_engine
real(kind=rkind), parameter :: true = 1._rkind
Functions
function wide_perceptron() result(trainable_engine)
Arguments
None
Return Value type(trainable_engine_t)
function wide_single_layer_perceptron() result(trainable_engine)
Arguments
None
Return Value type(trainable_engine_t)
Subroutines
subroutine output(engine, file_name)
Arguments
Type Intent Optional Attributes Name
type(trainable_engine_t), intent(in) :: engine
type(string_t), intent(in) :: file_name
Source Code
program train_xor_gate
  !! Define inference tests and procedures required for reporting results
  use string_m, only : string_t
  use trainable_engine_m, only : trainable_engine_t
  use inputs_m, only : inputs_t
  use outputs_m, only : outputs_t
  use expected_outputs_m, only : expected_outputs_t
  use matmul_m, only : matmul_t
  use kind_parameters_m, only : rkind
  use sigmoid_m, only : sigmoid_t
  use input_output_pair_m, only : input_output_pair_t
  use mini_batch_m, only : mini_batch_t
  use file_m, only : file_t
  use command_line_m, only : command_line_t
  implicit none
  real(rkind), parameter :: tolerance = 1.E-02_rkind, false = 0._rkind, true = 1._rkind
  type(outputs_t), dimension(4) :: actual_output
  type(expected_outputs_t), dimension(4) :: expected_outputs
  type(trainable_engine_t) trainable_engine
  type(command_line_t) command_line
  type(string_t) base_name
  type(mini_batch_t), allocatable :: mini_batches(:)
    type(inputs_t), allocatable :: inputs(:)
  character(len=5), parameter :: table_entry(*) = ["TT->F", "FT->T", "TF->T", "FF->F", "xor  "]
  integer i, m
  base_name = string_t(command_line%flag_value("--base-name"))
  if (len(base_name%string())==0) then
    error stop new_line('a') // new_line('a') // &
      'Usage: ./build/run-fpm.sh run --example train-xor-gate -- --base-name "<base-file-name>"'
  end if
  inputs = [ &
    inputs_t([true,true]), inputs_t([false,true]), inputs_t([true,false]), inputs_t([false,false]) &
  ]
  expected_outputs = [ &
    expected_outputs_t([false]), expected_outputs_t([true]), expected_outputs_t([true]), expected_outputs_t([false]) &
  ]
  print *,"Defining mini-batches, each containing input/output pairs corresponding to the four entries in the XOR truth table."
  mini_batches = [(mini_batch_t( input_output_pair_t( inputs, expected_outputs ) ), m=1,2000000)]
  print *,"Defining an initial trainable_engine_t neural network object."
  trainable_engine = wide_single_layer_perceptron()
  print *,"Training the neural network using the mini-batches. ___This could take a few minutes.___"
  call trainable_engine%train(mini_batches, matmul_t())
  associate(file_name => string_t(base_name%string() // ".json"))
    print *,"Writing the network parameters to "
    call output(trainable_engine, file_name)
  end associate
  print *,"Verifying that the network behaves as an exclusive-or (XOR) logic gate: "
  actual_output = trainable_engine%infer(inputs, matmul_t())
  if (any([(abs(actual_output(i)%outputs() - expected_outputs(i)%outputs()) < tolerance, i=1, size(actual_output))])) then
    print *,"Yes!"
  else
    error stop &
      "The trained network does not behave as a XOR gate.  " // &
      "Please report this issue at https://github.com/BerkeleyLab/inference-engine/issues."
  end if
contains
  subroutine output(engine, file_name)
    type(trainable_engine_t), intent(in) :: engine
    type(string_t), intent(in) :: file_name
    type(file_t) json_file
    json_file = trainable_engine%to_json()
    print *, "Writing an inference_engine_t object to the file '"//file_name%string()//"' in JSON format."
    call json_file%write_lines(file_name)
  end subroutine
  function wide_single_layer_perceptron() result(trainable_engine)
    type(trainable_engine_t) trainable_engine
    integer, parameter :: n_in = 2 ! number of inputs
    integer, parameter :: n_out = 1 ! number of outputs
    integer, parameter :: neurons = 3 ! number of neurons per layer
    integer, parameter :: n_hidden = 1 ! number of hidden layers
    trainable_engine = trainable_engine_t( &
      metadata = [ &
       string_t("Trainable XOR"), string_t("Damian Rouson"), string_t("2023-05-09"), string_t("sigmoid"), string_t("false") &
      ], &
      input_weights = real(reshape([1,0,1,1,0,1], [n_in, neurons]), rkind), &
      hidden_weights = reshape([real(rkind)::], [neurons,neurons,n_hidden-1]), &
      output_weights = real(reshape([1,-2,1], [n_out, neurons]), rkind), &
      biases = reshape([real(rkind):: 0.,-1.99,0.], [neurons, n_hidden]), &
      output_biases = [real(rkind):: 0.], &
      differentiable_activation_strategy = sigmoid_t() &
    )
  end function
  function wide_perceptron() result(trainable_engine)
    type(trainable_engine_t) trainable_engine
    integer, parameter :: n_in = 2 ! number of inputs
    integer, parameter :: n_out = 1 ! number of outputs
    integer, parameter :: neurons = 24 ! number of neurons per layer
    integer, parameter :: n_hidden = 1 ! number of hidden layers
    integer n
    trainable_engine = trainable_engine_t( &
      metadata = [ &
       string_t("Wide 1-layer perceptron"), string_t("Damian Rouson"), string_t("2023-05-24"), string_t("sigmoid"), string_t("false") &
      ], &
      input_weights = real(reshape([([1,0,1,1,0,1], n=1,8 )], [n_in, neurons]), rkind), &
      hidden_weights = reshape([real(rkind)::], [neurons,neurons,n_hidden-1]), &
      output_weights = real(reshape([([1,-2,1], n=1,8)], [n_out, neurons]), rkind), &
      biases = reshape([real(rkind):: [(0.,-1.99,0., n=1,8)] ], [neurons, n_hidden]), &
      output_biases = [real(rkind):: 0.], &
      differentiable_activation_strategy = sigmoid_t() &
    )
  end function
end program train_xor_gate
Call graph
train_xor_gate calls string_t, wide_single_layer_perceptron, output
wide_single_layer_perceptron calls string_t