write_read_infer – Inference-Engine
write_read_infer Program
51 statements
Source File
Uses
kind_parameters_m
inference_engine_m
julienne_m
This program demonstrates how to write a neural network to a JSON file, read the same network from the written file, query the network object for some of its properties, print those properties, and use the network to perform inference. The network performs an identity mapping from any non-negative inputs to the corresponding outputs using a RELU activation function.
Calls
Variables
Type Attributes Name Initial
type(command_line_t) :: command_line
type(string_t) :: file_name
Functions
function identity_network() result(inference_engine)
Arguments
None
Return Value type(inference_engine_t)
Subroutines
subroutine write_read_query_infer(output_file_name)
Arguments
Type Intent Optional Attributes Name
type(string_t), intent(in) :: output_file_name
Call graph
write_read_infer calls flag_value, write_read_query_infer, string, string_t
write_read_query_infer calls string, file_t, activation_function_name, infer, nodes_per_layer, num_inputs, num_outputs, to_json, values, identity_network, write_lines
identity_network calls string_t