module inference_engine_m
 use activation_strategy_m
 use concurrent_dot_products_m
 use differentiable_activation_strategy_m
 use inputs_m
 use inference_engine_m_
 use inference_strategy_m
 use kind_parameters_m
 use layer_m
 use matmul_m
 use mini_batch_m
 use neuron_m
 use outputs_m
 use sigmoid_m
 use step_m
 use swish_m
 use trainable_engine_m
 implicit none
end module
