name = "mypackage"
version = "0.1.0"
license = "license"
author = "Katherine Rasmussen"
maintainer = "krasmussen@lbl.gov"
copyright = "Copyright 2024, Katherine Rasmussen"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

